services: 
  app:
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_VARIANT=8.0
        - NODE_VERSION=lts
        - WORDPRESS_DB_HOST=mariadb
        - WORDPRESS_DB_USER=wordpress_db_usr
        - WORDPRESS_DB_PASSWORD=wordpress_db_pwd
        - WORDPRESS_DB_NAME=wordpress_db
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress_db_usr
      WORDPRESS_DB_PASSWORD: wordpress_db_pwd
      WORDPRESS_DB_NAME: wordpress_db
    restart: unless-stopped
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: mariadb:10.4
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_db_usr
      MYSQL_PASSWORD: wordpress_db_pwd
      
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db

volumes:
  mariadb-data:
